export interface FieldProperty {
  id?: string;
  name: string;
  type: string;
  valueType: string;
  format: string;
  generationType: string;
  isMandatory: boolean;
  isAutoGenerated: boolean;
}

export interface Contract {
  id?: string;
  schemaMode: 'file' | 'json';
  schemaContent: string;
  baseMode: 'file' | 'json';
  baseContent: string;
  fieldProperties: FieldProperty[];
}
