import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { HeaderService } from '../../../core/services/header.service';
import { LoadingService } from '../../../core/services/loading.service';
import { SharedModule } from '../../../shared/shared.module';
import { FieldProperty } from '../../../core/models/contract.model';

/**
 * ContractPropertiesComponent handles both addition and editing of individual
 * field properties for a contract. It integrates with global shell services.
 */
@Component({
  selector: 'app-contract-properties',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, SharedModule],
  templateUrl: './contract-properties.component.html',
  styleUrls: ['./contract-properties.component.scss']
})
export class ContractPropertiesComponent implements OnInit {
  propertyForm!: FormGroup;
  isEditMode = false;
  contractId: string | null = null;
  propertyId: string | null = null;
  savedProperties: FieldProperty[] = [];

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private headerService: HeaderService,
    private loadingService: LoadingService
  ) {
    this.initForm();
  }

  ngOnInit(): void {
    // Subscribe to route parameters to handle component reuse
    this.route.paramMap.subscribe(params => {
      this.contractId = params.get('contractId');
      this.propertyId = params.get('id');
      this.isEditMode = !!this.propertyId;

      if (this.propertyId) {
        this.fetchPropertyById(this.propertyId);
      } else {
        this.propertyForm.reset({
          type: 'String',
          generationType: 'Random',
          isMandatory: false,
          isAutoGenerated: false
        });
      }

      this.updateHeader();
      this.fetchPropertiesByContractId();
    });
  }

  /**
   * Initializes the property configuration form.
   */
  private initForm(): void {
    this.propertyForm = this.fb.group({
      name: ['', Validators.required],
      type: ['String', Validators.required],
      valueType: [''],
      format: [''],
      generationType: ['Random'],
      isMandatory: [false],
      isAutoGenerated: [false]
    });
  }

  /**
   * Updates the global header with dynamic title, breadcrumbs, and description.
   */
  private updateHeader(): void {
    const title = this.isEditMode ? 'Edit Property' : 'Contract Properties';
    const breadcrumbs = [
      { label: 'Contracts', route: '/contracts/new' },
      { label: 'Contract Details', route: `/contracts/edit/${this.contractId || ''}` },
      { label: 'Contract Properties', route: this.router.url }
    ];
    const description = 'Configure technical field-level validation and generation rules.';

    this.headerService.setHeader(title, breadcrumbs, description);
  }

  /**
   * Fetches a specific property by ID for editing (Placeholder).
   */
  private fetchPropertyById(id: string): void {
    this.loadingService.show();
    console.log(`Fetching property by ID: ${id}`);

    // Simulating API call
    setTimeout(() => {
      /*
      API PLACEHOLDER: GET /api/contracts/:contractId/properties/:id
      this.contractService.getProperty(this.contractId, id).subscribe(prop => {
        this.propertyForm.patchValue(prop);
        this.loadingService.hide();
      });
      */

      // Mock data population for demo
      if (id === 'user_id') {
        this.propertyForm.patchValue({
          name: 'user_id',
          type: 'Long',
          valueType: 'UUID',
          format: 'UUID',
          generationType: 'Random',
          isMandatory: true,
          isAutoGenerated: false
        });
      }
      this.loadingService.hide();
    }, 800);
  }

  /**
   * Fetches all properties associated with the current contract (Placeholder).
   */
  private fetchPropertiesByContractId(): void {
    this.loadingService.show();

    // Simulating API call
    setTimeout(() => {
      /*
      API PLACEHOLDER: GET /api/contracts/:contractId/properties
      this.contractService.getProperties(this.contractId).subscribe(properties => {
        this.savedProperties = properties;
        this.loadingService.hide();
      });
      */

      // Mock data for "Saved Properties" list
      this.savedProperties = [
        {
          id: 'user_id',
          name: 'user_id',
          type: 'LONG',
          valueType: '',
          format: '',
          generationType: '',
          isMandatory: true,
          isAutoGenerated: false
        },
        {
          id: 'contact_email',
          name: 'contact_email',
          type: 'STRING',
          valueType: '',
          format: 'EMAIL FORMAT',
          generationType: '',
          isMandatory: false,
          isAutoGenerated: false
        },
        {
          id: 'created_at',
          name: 'created_at',
          type: 'STRING',
          valueType: '',
          format: '',
          generationType: '',
          isMandatory: false,
          isAutoGenerated: true
        }
      ];
      this.loadingService.hide();
    }, 800);
  }

  /**
   * Handles form submission for adding or updating a property.
   */
  onSubmit(): void {
    if (this.propertyForm.invalid) {
      return;
    }

    this.loadingService.show();
    const formData = this.propertyForm.value;
    console.log('Submitting property data:', formData);

    setTimeout(() => {
      if (this.isEditMode) {
        /*
        API PLACEHOLDER: PUT /api/contracts/:contractId/properties/:id
        this.contractService.updateProperty(this.contractId!, this.propertyId!, formData).subscribe(() => {
          this.loadingService.hide();
          this.router.navigate(['/contracts', this.contractId, 'properties']);
        });
        */
        console.log('Update successful');
      } else {
        /*
        API PLACEHOLDER: POST /api/contracts/:contractId/properties
        this.contractService.createProperty(this.contractId!, formData).subscribe(() => {
          this.loadingService.hide();
          this.propertyForm.reset({type: 'String', generationType: 'Random'});
          this.fetchPropertiesByContractId();
        });
        */
        console.log('Creation successful');
        this.propertyForm.reset({type: 'String', generationType: 'Random', isMandatory: false, isAutoGenerated: false});
      }
      this.loadingService.hide();
      this.fetchPropertiesByContractId();
    }, 1200);
  }

  /**
   * Navigates to the edit view for a specific property.
   */
  onEdit(prop: FieldProperty): void {
    if (this.contractId && prop.id) {
      this.router.navigate(['/contracts', this.contractId, 'properties', prop.id]);
    }
  }

  /**
   * Placeholder for property deletion.
   */
  onDelete(prop: FieldProperty): void {
    console.log('Deleting property:', prop.id);
    // Implementation for DELETE /api/contracts/:contractId/properties/:id
  }
}
